version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    networks:
      - my-red
  nginx:
    container_name: nginx_gateway
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - spring-boot-app
    networks:
      - my-red

networks:
  my-red:
    driver: bridge
      
