version: '3'

services:
  spring-boot-app:
    image: fercdevv/demo-spring-boot-app:latest
    ports:
      - "5000"
    networks:
      - my-red
  nginx:
    container_name: nginx_gateway
    image: fercdevv/demo-nginx:latest
    ports:
      - 8080:80
    depends_on:
      - spring-boot-app
    networks:
      - my-red

networks:
  my-red:
    driver: bridge
      
